name: Update Discord Class Names
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Class Name Updater
        uses: fedeericodl/discord-update-classnames@main
        with:
          files: "src/components/"